"""core tables

Revision ID: 0001_core
Revises:
Create Date: 2026-07-08 13:34:30.218625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_core'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitor_comments',
    sa.Column('post_source_id', sa.String(length=128), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('window_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', name='uq_competitor_comments_source_id')
    )
    op.create_index(op.f('ix_competitor_comments_post_source_id'), 'competitor_comments', ['post_source_id'], unique=False)
    op.create_index(op.f('ix_competitor_comments_window_date'), 'competitor_comments', ['window_date'], unique=False)
    op.create_table('competitor_posts',
    sa.Column('competitor', sa.String(length=128), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('window_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', name='uq_competitor_posts_source_id')
    )
    op.create_index(op.f('ix_competitor_posts_competitor'), 'competitor_posts', ['competitor'], unique=False)
    op.create_index(op.f('ix_competitor_posts_window_date'), 'competitor_posts', ['window_date'], unique=False)
    op.create_table('generated_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=False),
    sa.Column('source_feature', sa.String(length=64), nullable=False),
    sa.Column('prefill_prompt', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('google_reviews',
    sa.Column('star_rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('reviewer', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('window_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', name='uq_google_reviews_source_id')
    )
    op.create_index(op.f('ix_google_reviews_window_date'), 'google_reviews', ['window_date'], unique=False)
    op.create_table('keyword_volumes',
    sa.Column('keyword', sa.String(length=256), nullable=False),
    sa.Column('weekly_search_volume', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('window_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', name='uq_keyword_volumes_source_id')
    )
    op.create_index(op.f('ix_keyword_volumes_keyword'), 'keyword_volumes', ['keyword'], unique=False)
    op.create_index(op.f('ix_keyword_volumes_window_date'), 'keyword_volumes', ['window_date'], unique=False)
    op.create_table('own_posts',
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('interactions', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('window_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', name='uq_own_posts_source_id')
    )
    op.create_index(op.f('ix_own_posts_window_date'), 'own_posts', ['window_date'], unique=False)
    op.create_table('post_comments',
    sa.Column('post_source_id', sa.String(length=128), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('window_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', name='uq_post_comments_source_id')
    )
    op.create_index(op.f('ix_post_comments_post_source_id'), 'post_comments', ['post_source_id'], unique=False)
    op.create_index(op.f('ix_post_comments_window_date'), 'post_comments', ['window_date'], unique=False)
    op.create_table('saved_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zoho_chats',
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('window_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', name='uq_zoho_chats_source_id')
    )
    op.create_index(op.f('ix_zoho_chats_window_date'), 'zoho_chats', ['window_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zoho_chats_window_date'), table_name='zoho_chats')
    op.drop_table('zoho_chats')
    op.drop_table('saved_drafts')
    op.drop_index(op.f('ix_post_comments_window_date'), table_name='post_comments')
    op.drop_index(op.f('ix_post_comments_post_source_id'), table_name='post_comments')
    op.drop_table('post_comments')
    op.drop_index(op.f('ix_own_posts_window_date'), table_name='own_posts')
    op.drop_table('own_posts')
    op.drop_index(op.f('ix_keyword_volumes_window_date'), table_name='keyword_volumes')
    op.drop_index(op.f('ix_keyword_volumes_keyword'), table_name='keyword_volumes')
    op.drop_table('keyword_volumes')
    op.drop_index(op.f('ix_google_reviews_window_date'), table_name='google_reviews')
    op.drop_table('google_reviews')
    op.drop_table('generated_posts')
    op.drop_index(op.f('ix_competitor_posts_window_date'), table_name='competitor_posts')
    op.drop_index(op.f('ix_competitor_posts_competitor'), table_name='competitor_posts')
    op.drop_table('competitor_posts')
    op.drop_index(op.f('ix_competitor_comments_window_date'), table_name='competitor_comments')
    op.drop_index(op.f('ix_competitor_comments_post_source_id'), table_name='competitor_comments')
    op.drop_table('competitor_comments')
    # ### end Alembic commands ###
